-- Table and job: inventory_daily_count (like base_reportcountinventory)
-- Truncate and repopulate with daily VIN counts per customer for the last 30 days. Run via cron.

-- ============================================================
-- 1. Table: inventory_daily_count (id, customer_id, pull_date, vin_count)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.inventory_daily_count (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  bigint NULL,
  pull_date    date NULL,
  vin_count    integer NOT NULL DEFAULT 0,
  CONSTRAINT inventory_daily_count_customer_id_fkey
    FOREIGN KEY (customer_id) REFERENCES public.clients(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_inventory_daily_count_customer_id
  ON public.inventory_daily_count (customer_id);
CREATE INDEX IF NOT EXISTS idx_inventory_daily_count_pull_date
  ON public.inventory_daily_count (pull_date);
CREATE INDEX IF NOT EXISTS idx_inventory_daily_count_customer_pull
  ON public.inventory_daily_count (customer_id, pull_date);

COMMENT ON TABLE public.inventory_daily_count IS 'Daily VIN count per customer (last 30 days). Refreshed by run_inventory_daily_count().';

-- ============================================================
-- 2. Function: truncate + insert aggregated counts from inventorydata (last 30 days)
-- ============================================================
CREATE OR REPLACE FUNCTION public.run_inventory_daily_count()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_from_date date := CURRENT_DATE - INTERVAL '30 days';
  v_to_date   date := CURRENT_DATE;
  v_inserted  bigint;
BEGIN
  TRUNCATE TABLE public.inventory_daily_count;

  INSERT INTO public.inventory_daily_count (customer_id, pull_date, vin_count)
  SELECT
    i.customer_id,
    (i.pull_date::date) AS pull_date,
    COUNT(*)::integer   AS vin_count
  FROM public.inventorydata i
  INNER JOIN public.clients c ON c.id = i.customer_id
   AND (CASE WHEN c.is_active IS TRUE THEN 1 WHEN c.is_active IS FALSE THEN 0 ELSE COALESCE(c.is_active::int, 0) END) = 1
  WHERE i.pull_date >= v_from_date
    AND i.pull_date <= v_to_date
    AND i.customer_id IS NOT NULL
  GROUP BY i.customer_id, (i.pull_date::date)
  ORDER BY i.customer_id, i.pull_date;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  RETURN jsonb_build_object(
    'status',        'ok',
    'rows_inserted', v_inserted,
    'from_date',     v_from_date,
    'to_date',       v_to_date
  );
END;
$$;

COMMENT ON FUNCTION public.run_inventory_daily_count() IS 'Truncates inventory_daily_count and repopulates with daily VIN counts per customer for the last 30 days from inventorydata.';

-- ============================================================
-- 3. Grants
-- ============================================================
GRANT SELECT, INSERT, TRUNCATE ON public.inventory_daily_count TO service_role;
GRANT SELECT ON public.inventory_daily_count TO authenticated;
GRANT EXECUTE ON FUNCTION public.run_inventory_daily_count() TO service_role;
GRANT EXECUTE ON FUNCTION public.run_inventory_daily_count() TO postgres;

-- ============================================================
-- 4. Cron: run daily (e.g. 4:00 AM, after normalized -> inventorydata)
-- ============================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'inventory-daily-count') THEN
    PERFORM cron.unschedule('inventory-daily-count');
  END IF;
END $$;

SELECT cron.schedule(
  'inventory-daily-count',
  '0 4 * * *',
  $$SELECT public.run_inventory_daily_count()$$
);
