-- Table and job: sales_daily_count (like inventory_daily_count)
-- Truncate and repopulate with daily sales counts per customer for the last 30 days, derived from saleprocessedvins.final_sold_date.

-- ============================================================
-- 1. Table: sales_daily_count (id, customer_id, sold_date, sale_count)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.sales_daily_count (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  bigint NULL,
  sold_date    date NULL,
  sale_count   integer NOT NULL DEFAULT 0,
  CONSTRAINT sales_daily_count_customer_id_fkey
    FOREIGN KEY (customer_id) REFERENCES public.clients(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_sales_daily_count_customer_id
  ON public.sales_daily_count (customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_daily_count_sold_date
  ON public.sales_daily_count (sold_date);
CREATE INDEX IF NOT EXISTS idx_sales_daily_count_customer_sold
  ON public.sales_daily_count (customer_id, sold_date);

COMMENT ON TABLE public.sales_daily_count IS 'Daily sales count per customer (last 30 days). Refreshed by run_sales_daily_count().';

-- ============================================================
-- 2. Function: truncate + insert aggregated counts from saleprocessedvins (last 30 days)
-- ============================================================
CREATE OR REPLACE FUNCTION public.run_sales_daily_count()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_from_date date := (CURRENT_DATE - INTERVAL '29 days')::date;
  v_to_date   date := CURRENT_DATE::date;
  v_inserted  bigint;
BEGIN
  TRUNCATE TABLE public.sales_daily_count;

  INSERT INTO public.sales_daily_count (customer_id, sold_date, sale_count)
  SELECT
    s.customer_id,
    (s.final_sold_date::date) AS sold_date,
    COUNT(*)::integer         AS sale_count
  FROM public.saleprocessedvins s
  INNER JOIN public.clients c ON c.id = s.customer_id
   AND (CASE WHEN c.is_active IS TRUE THEN 1 WHEN c.is_active IS FALSE THEN 0 ELSE COALESCE(c.is_active::int, 0) END) = 1
  WHERE s.final_sold_date IS NOT NULL
    AND s.customer_id IS NOT NULL
    AND s.final_sold_date::date >= v_from_date
    AND s.final_sold_date::date <= v_to_date
  GROUP BY s.customer_id, (s.final_sold_date::date)
  ORDER BY s.customer_id, (s.final_sold_date::date);

  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  RETURN jsonb_build_object(
    'status',        'ok',
    'rows_inserted', v_inserted,
    'from_date',     v_from_date,
    'to_date',       v_to_date
  );
END;
$$;

COMMENT ON FUNCTION public.run_sales_daily_count() IS 'Truncates sales_daily_count and repopulates with daily sales counts per customer for the last 30 days from saleprocessedvins.final_sold_date.';

-- ============================================================
-- 3. Grants
-- ============================================================
GRANT SELECT, INSERT, TRUNCATE ON public.sales_daily_count TO service_role;
GRANT SELECT ON public.sales_daily_count TO authenticated;
GRANT EXECUTE ON FUNCTION public.run_sales_daily_count() TO service_role;
GRANT EXECUTE ON FUNCTION public.run_sales_daily_count() TO postgres;

-- ============================================================
-- 4. Cron: run daily (after daily sales processing)
-- ============================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'sales-daily-count') THEN
    PERFORM cron.unschedule('sales-daily-count');
  END IF;
END $$;

-- Runs at 05:25 and 11:25 UTC.
SELECT cron.schedule(
  'sales-daily-count',
  '25 5,11 * * *',
  $$SELECT public.run_sales_daily_count()$$
);

