-- Mirror Python utils: client mapping from clients.dealership_name + custom lookup tables.
-- Run after 20260317000003. Sync will use clients table and lookups for custom_make, custom_type, custom_condition, custom_model_trim.

-- ============================================================
-- 1. clients.dealership_name (for get_client_dealership_mapping)
-- ============================================================
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS dealership_name text;

COMMENT ON COLUMN public.clients.dealership_name IS 'Matches scrap_rawdata.dealership_name; used by run_normalized_inventory_from_scrap. Filter: not null, not empty, is_active.';

-- ============================================================
-- 2. Lookup tables (Custommaketext, Customtypetext, Customconditiontext, CustomModelTrim)
-- ============================================================

-- make_text (lower) -> custom_make_text
CREATE TABLE IF NOT EXISTS public.custom_make_text (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  make_text         text NOT NULL,
  custom_make_text  text NOT NULL,
  UNIQUE (make_text)
);

CREATE INDEX IF NOT EXISTS idx_custom_make_text_lower
  ON public.custom_make_text (LOWER(make_text));

-- type_text (lower) -> custom_type_text
CREATE TABLE IF NOT EXISTS public.custom_type_text (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_text          text NOT NULL,
  custom_type_text   text NOT NULL,
  UNIQUE (type_text)
);

CREATE INDEX IF NOT EXISTS idx_custom_type_text_lower
  ON public.custom_type_text (LOWER(type_text));

-- condition_text (lower) -> custom_condition_text
CREATE TABLE IF NOT EXISTS public.custom_condition_text (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condition_text        text NOT NULL,
  custom_condition_text text NOT NULL,
  UNIQUE (condition_text)
);

CREATE INDEX IF NOT EXISTS idx_custom_condition_text_lower
  ON public.custom_condition_text (LOWER(condition_text));

-- (model, trim, title) lower -> (custom_model, custom_trim)
CREATE TABLE IF NOT EXISTS public.custom_model_trim (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model        text NOT NULL,
  trim         text NOT NULL,
  title        text NOT NULL,
  custom_model text NOT NULL,
  custom_trim  text NOT NULL,
  UNIQUE (model, trim, title)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_custom_model_trim_lower
  ON public.custom_model_trim (LOWER(TRIM(COALESCE(model, ''))), LOWER(TRIM(COALESCE(trim, ''))), LOWER(TRIM(COALESCE(title, ''))));

-- ============================================================
-- 3. Sync function: use clients.dealership_name + lookups
--    choose_custom_type: type_ + ' ' + sub_type when sub_type present, else type_
--    normalise_custom_type(custom_type) -> custom_type_2
--    choose_custom_make(make) -> custom_make
--    normalise_custom_condition(condition_) -> custom_condition
--    normalise_custom_model_trim(model, trim, title) -> custom_model, custom_trim
-- ============================================================
CREATE OR REPLACE FUNCTION public.run_normalized_inventory_from_scrap(p_date date DEFAULT CURRENT_DATE)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_inserted bigint;
  v_pull_ts  timestamptz := clock_timestamp();
BEGIN
  IF p_date IS NULL THEN
    p_date := CURRENT_DATE;
  END IF;

  INSERT INTO public.normalized_inventory_from_scrap (
    customer_id,
    track_date,
    pull_date,
    pull_date_time,
    "condition",
    year,
    make,
    model,
    vin,
    advertiser,
    color,
    description,
    doors,
    drivetrain,
    formatted_price,
    fuel_type,
    image_type,
    image_url,
    location,
    mileage,
    price,
    title,
    transmission,
    trim,
    type,
    url,
    vehicle_type,
    custom_label_0,
    custom_label_1,
    custom_label_2,
    custom_label_3,
    custom_label_4,
    custom_type,
    rv_type,
    rv_category,
    rv_class,
    category,
    motorhome_class,
    custom_make,
    custom_type_2,
    custom_condition,
    cms,
    sale_tag,
    stock_number,
    msrp,
    custom_model,
    custom_trim
  )
  SELECT
    c.id,
    r.creation_date,
    r.creation_date,
    v_pull_ts,
    r.condition_,
    r.year_,
    r.make,
    r.model,
    r.vin,
    COALESCE(r.dealer_url, '')::varchar(255),
    COALESCE(r.exterior_color, '')::varchar(255),
    r.description,
    r.doors,
    r.drivetrain,
    r.price,
    r.fuel_type,
    ''::varchar(255),
    r.image_url,
    CASE
      WHEN c.id IN (143, 144, 145, 146, 147, 150, 151) THEN 'Location one'
      ELSE COALESCE(REPLACE(r.location, ',', ''), '')
    END,
    TRIM(COALESCE(r.mileage_value, '') || ' ' || COALESCE(r.mileage_unit, ''))::varchar(255),
    COALESCE(
      NULLIF(TRIM(REGEXP_REPLACE(COALESCE(r.price, ''), '[,$]', '', 'g')), ''),
      '0.00'
    )::varchar(255),
    r.title,
    r.transmission,
    r.trim,
    r.type_,
    COALESCE(r.url, '')::varchar(255),
    ''::varchar(255),
    r.custom_label_0,
    r.custom_label_1,
    r.custom_label_2,
    ''::varchar(255),
    ''::varchar(255),
    -- choose_custom_type: type + ' ' + sub_type when sub_type present, else type
    TRIM(COALESCE(r.type_, '') || CASE WHEN COALESCE(TRIM(r.sub_type), '') <> '' THEN ' ' || r.sub_type ELSE '' END)::varchar(255),
    ''::varchar(255),
    ''::varchar(255),
    ''::varchar(255),
    r.sub_type,
    ''::varchar(255),
    -- custom_make: lookup by LOWER(make)
    COALESCE(
      (SELECT cm.custom_make_text FROM public.custom_make_text cm WHERE LOWER(TRIM(COALESCE(r.make, ''))) = LOWER(cm.make_text) LIMIT 1),
      ''
    )::varchar(255),
    -- custom_type_2: normalise_custom_type(custom_type) — lookup by LOWER(custom_type); custom_type is type_ + sub_type above
    COALESCE(
      (SELECT ct.custom_type_text FROM public.custom_type_text ct
       WHERE LOWER(TRIM(COALESCE(r.type_, '') || CASE WHEN COALESCE(TRIM(r.sub_type), '') <> '' THEN ' ' || r.sub_type ELSE '' END)) = LOWER(ct.type_text)
       LIMIT 1),
      ''
    )::varchar(255),
    -- custom_condition: normalise_custom_condition(condition_)
    COALESCE(
      (SELECT cc.custom_condition_text FROM public.custom_condition_text cc
       WHERE LOWER(TRIM(COALESCE(r.condition_, ''))) = LOWER(cc.condition_text)
       LIMIT 1),
      ''
    )::varchar(255),
    r.cms,
    r.special_tag,
    r.stock_number,
    r.msrp,
    -- custom_model, custom_trim: normalise_custom_model_trim(model, trim, title)
    COALESCE(
      (SELECT cmt.custom_model FROM public.custom_model_trim cmt
       WHERE LOWER(TRIM(COALESCE(r.model, ''))) = LOWER(TRIM(COALESCE(cmt.model, '')))
         AND LOWER(TRIM(COALESCE(r.trim, ''))) = LOWER(TRIM(COALESCE(cmt.trim, '')))
         AND LOWER(TRIM(COALESCE(r.title, ''))) = LOWER(TRIM(COALESCE(cmt.title, '')))
       LIMIT 1),
      ''
    )::varchar(255),
    COALESCE(
      (SELECT cmt.custom_trim FROM public.custom_model_trim cmt
       WHERE LOWER(TRIM(COALESCE(r.model, ''))) = LOWER(TRIM(COALESCE(cmt.model, '')))
         AND LOWER(TRIM(COALESCE(r.trim, ''))) = LOWER(TRIM(COALESCE(cmt.trim, '')))
         AND LOWER(TRIM(COALESCE(r.title, ''))) = LOWER(TRIM(COALESCE(cmt.title, '')))
       LIMIT 1),
      ''
    )::varchar(255)
  FROM public.scrap_rawdata r
  INNER JOIN public.clients c
    ON c.dealership_name IS NOT NULL
   AND TRIM(c.dealership_name) <> ''
   AND c.is_active = TRUE
   AND c.dealership_name = r.dealership_name
  WHERE r.creation_date = p_date
  ON CONFLICT (customer_id, pull_date, vin, url) DO NOTHING;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  RETURN jsonb_build_object(
    'date', p_date,
    'rows_inserted', v_inserted,
    'status', 'ok'
  );
END;
$$;

COMMENT ON FUNCTION public.run_normalized_inventory_from_scrap(date) IS 'Syncs scrap_rawdata into normalized_inventory_from_scrap. Uses clients.dealership_name (active, non-empty) and lookup tables: custom_make_text, custom_type_text, custom_condition_text, custom_model_trim.';

-- Grants for lookups (service_role used by cron)
GRANT SELECT ON public.custom_make_text TO service_role;
GRANT SELECT ON public.custom_type_text TO service_role;
GRANT SELECT ON public.custom_condition_text TO service_role;
GRANT SELECT ON public.custom_model_trim TO service_role;
