-- Table: hoot_inventory
-- Hoot (active pull) inventory feed — structure + indexes aligned with MySQL / phpMyAdmin exports.
-- Unique natural key: (customer_id, pull_date, vin, url)

CREATE TABLE IF NOT EXISTS public.hoot_inventory (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id       bigint
    REFERENCES public.clients (id) ON DELETE SET NULL,
  pull_date_time    timestamp(6) without time zone,
  pull_date         date,
  "condition"       varchar(255),
  year              varchar(255),
  make              varchar(255),
  model             varchar(255),
  vin               varchar(255),
  advertiser        varchar(255),
  color             varchar(255),
  description       varchar(255),
  doors             varchar(255),
  drivetrain        varchar(255),
  formatted_price   varchar(255),
  fuel_type         varchar(255),
  image_type        varchar(255),
  image_url         varchar(255),
  location          varchar(255),
  mileage           varchar(255),
  price             varchar(255),
  title             varchar(255),
  transmission      varchar(255),
  trim              varchar(255),
  type              varchar(255),
  url               varchar(255),
  vehicle_type      varchar(255),
  custom_label_0    varchar(255),
  custom_label_1    varchar(255),
  custom_label_2    varchar(255),
  custom_label_3    varchar(255),
  custom_label_4    varchar(255),
  custom_type       varchar(255),
  rv_type           varchar(255),
  rv_category       varchar(255),
  rv_class          varchar(255),
  category          varchar(255),
  motorhome_class   varchar(255),
  custom_make       varchar(255),
  custom_type_2     varchar(255),
  custom_condition  varchar(255),
  custom_model      varchar(255),
  custom_trim       varchar(255)
);

COMMENT ON TABLE public.hoot_inventory IS
  'Inventory rows from Hoot / active pull feed. Unique per (customer_id, pull_date, vin, url).';

-- ---------------------------------------------------------------------------
-- Indexes (MySQL: unique on customer_id + pull_date + vin + url; btree on customer_id+pull_date; keys on pull_date, vin, url)
-- ---------------------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS idx_hoot_inventory_customer_pull_vin_url
  ON public.hoot_inventory (customer_id, pull_date, vin, url);

CREATE INDEX IF NOT EXISTS idx_hoot_inventory_customer_pull
  ON public.hoot_inventory (customer_id, pull_date);

CREATE INDEX IF NOT EXISTS idx_hoot_inventory_customer_id
  ON public.hoot_inventory (customer_id);

CREATE INDEX IF NOT EXISTS idx_hoot_inventory_pull_date
  ON public.hoot_inventory (pull_date);

CREATE INDEX IF NOT EXISTS idx_hoot_inventory_vin
  ON public.hoot_inventory (vin);

CREATE INDEX IF NOT EXISTS idx_hoot_inventory_url
  ON public.hoot_inventory (url);

-- ---------------------------------------------------------------------------
-- Optional helper: same idea as get_inventory_customer_count() for dashboard
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.get_hoot_inventory_customer_count()
RETURNS bigint
LANGUAGE sql
STABLE
AS $$
  SELECT COUNT(DISTINCT customer_id)::bigint
  FROM public.hoot_inventory
  WHERE customer_id IS NOT NULL;
$$;

COMMENT ON FUNCTION public.get_hoot_inventory_customer_count() IS
  'Returns count of distinct customer_id in hoot_inventory (for dashboard).';

GRANT EXECUTE ON FUNCTION public.get_hoot_inventory_customer_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_hoot_inventory_customer_count() TO service_role;

-- ---------------------------------------------------------------------------
-- Access (RLS + grants)
-- ---------------------------------------------------------------------------

ALTER TABLE public.hoot_inventory ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hoot_inventory_select_authenticated" ON public.hoot_inventory;
CREATE POLICY "hoot_inventory_select_authenticated"
  ON public.hoot_inventory
  FOR SELECT
  TO authenticated
  USING (true);

COMMENT ON POLICY "hoot_inventory_select_authenticated" ON public.hoot_inventory IS
  'Read-only for signed-in users; writes use service_role or additional policies as needed.';

GRANT SELECT ON TABLE public.hoot_inventory TO authenticated;
GRANT ALL ON TABLE public.hoot_inventory TO service_role;
