-- SendGrid Event Webhook storage (parity with Django SendGridEvent model + raw row JSON).

CREATE TABLE IF NOT EXISTS public.sendgrid_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  entry_date date NOT NULL DEFAULT CURRENT_DATE,

  email text,
  event text,
  mc_auto_name text,
  mc_auto_unique_id text,
  asm_group_id text,
  ip text,
  mc_auto_id text,
  mc_auto_msg_id text,
  mc_auto_step_id text,
  mc_pod_id text,
  mc_stats text,
  sg_event_id text,
  sg_message_id text,
  sg_template_id text,
  template_hash text,
  template_id text,
  template_version_id text,
  -- SendGrid sends Unix seconds; nullable if missing or non-numeric
  event_timestamp bigint,
  url text,

  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb
);

COMMENT ON TABLE public.sendgrid_events IS 'SendGrid Event Webhook payloads (one row per event in the posted array).';

CREATE INDEX IF NOT EXISTS sendgrid_events_created_at_idx ON public.sendgrid_events (created_at DESC);
CREATE INDEX IF NOT EXISTS sendgrid_events_entry_date_idx ON public.sendgrid_events (entry_date);
CREATE INDEX IF NOT EXISTS sendgrid_events_event_idx ON public.sendgrid_events (event);
CREATE INDEX IF NOT EXISTS sendgrid_events_email_idx ON public.sendgrid_events (email);

ALTER TABLE public.sendgrid_events ENABLE ROW LEVEL SECURITY;

-- No policies for anon/authenticated: only service_role (Edge Functions) bypasses RLS and can insert/select.

GRANT SELECT ON public.sendgrid_events TO authenticated;
GRANT SELECT, INSERT ON public.sendgrid_events TO service_role;
-- Intentionally no INSERT/UPDATE/DELETE for authenticated; use Dashboard SQL or service role.
