-- Table: normalized_inventory_from_scrap
-- Based on MySQL table scrap_normalized_inventory (structure + indexes).

CREATE TABLE IF NOT EXISTS public.normalized_inventory_from_scrap (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id       bigint,
  pull_date_time    timestamp(6) with time zone,
  pull_date         date,
  "condition"       varchar(255),
  year              varchar(255),
  make              varchar(255),
  model             varchar(255),
  vin               varchar(255),
  advertiser        varchar(255),
  color             varchar(255),
  description       varchar(255),
  doors             varchar(255),
  drivetrain        varchar(255),
  formatted_price   varchar(255),
  fuel_type         varchar(255),
  image_type        varchar(255),
  image_url         varchar(255),
  location          varchar(255),
  mileage           varchar(255),
  price             varchar(255),
  title             varchar(255),
  transmission      varchar(255),
  trim              varchar(255),
  type              varchar(255),
  url               varchar(255),
  vehicle_type      varchar(255),
  custom_label_0    varchar(255),
  custom_label_1    varchar(255),
  custom_label_2    varchar(255),
  custom_label_3    varchar(255),
  custom_label_4    varchar(255),
  custom_type       varchar(255),
  rv_type           varchar(255),
  rv_category       varchar(255),
  rv_class          varchar(255),
  category          varchar(255),
  motorhome_class   varchar(255),
  custom_make       varchar(255),
  custom_type_2     varchar(255),
  track_date        date,
  custom_condition  varchar(255),
  cms               varchar(255),
  sale_tag          varchar(255),
  stock_number      varchar(255),
  msrp              varchar(255),
  custom_model      varchar(255),
  custom_trim        varchar(255)
);

-- Unique index: (customer_id, pull_date, vin, url) — prevents duplicate rows per customer/date/vin/url
CREATE UNIQUE INDEX IF NOT EXISTS idx_normalized_inv_scrap_customer_pull_vin_url
  ON public.normalized_inventory_from_scrap (customer_id, pull_date, vin, url);

-- Single-column B-tree indexes for common filters
CREATE INDEX IF NOT EXISTS idx_normalized_inv_scrap_customer_id
  ON public.normalized_inventory_from_scrap (customer_id);

CREATE INDEX IF NOT EXISTS idx_normalized_inv_scrap_pull_date
  ON public.normalized_inventory_from_scrap (pull_date);

CREATE INDEX IF NOT EXISTS idx_normalized_inv_scrap_track_date
  ON public.normalized_inventory_from_scrap (track_date);

-- Optional: enable RLS and add policies if you need row-level security (uncomment and adjust as needed)
-- ALTER TABLE public.normalized_inventory_from_scrap ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow read for authenticated" ON public.normalized_inventory_from_scrap FOR SELECT TO authenticated USING (true);

COMMENT ON TABLE public.normalized_inventory_from_scrap IS 'Normalized inventory from scrap; structure mirrors MySQL scrap_normalized_inventory.';
