-- Create lookup tables with MySQL names (no base_ prefix): customtypetext, custommaketext, customconditiontext, custom_model_trim
-- Seed with data from MySQL. Sync function will use these tables.
-- If migration 000004 created custom_make_text, custom_type_text, custom_condition_text, we rename them and update the function.

-- ============================================================
-- 1. Rename tables from 000004 to match MySQL names (no base_)
-- ============================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'custom_make_text') THEN
    ALTER TABLE public.custom_make_text RENAME TO custommaketext;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'custom_type_text') THEN
    ALTER TABLE public.custom_type_text RENAME TO customtypetext;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'custom_condition_text') THEN
    ALTER TABLE public.custom_condition_text RENAME TO customconditiontext;
  END IF;
END $$;

-- Create tables if they don't exist (e.g. 000004 not run or different order)
CREATE TABLE IF NOT EXISTS public.custommaketext (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  make_text         text NOT NULL,
  custom_make_text  text NOT NULL,
  UNIQUE (make_text)
);
CREATE INDEX IF NOT EXISTS idx_custommaketext_lower ON public.custommaketext (LOWER(make_text));

CREATE TABLE IF NOT EXISTS public.customtypetext (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_text          text NOT NULL,
  custom_type_text   text NOT NULL,
  UNIQUE (type_text)
);
CREATE INDEX IF NOT EXISTS idx_customtypetext_lower ON public.customtypetext (LOWER(type_text));

CREATE TABLE IF NOT EXISTS public.customconditiontext (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condition_text        text NOT NULL,
  custom_condition_text text NOT NULL,
  UNIQUE (condition_text)
);
CREATE INDEX IF NOT EXISTS idx_customconditiontext_lower ON public.customconditiontext (LOWER(condition_text));

-- custom_model_trim: already created in 000004 with this name; create if missing
CREATE TABLE IF NOT EXISTS public.custom_model_trim (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model        text NOT NULL,
  trim         text NOT NULL,
  title        text NOT NULL,
  custom_model text NOT NULL,
  custom_trim  text NOT NULL,
  UNIQUE (model, trim, title)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_custom_model_trim_lower
  ON public.custom_model_trim (LOWER(TRIM(COALESCE(model, ''))), LOWER(TRIM(COALESCE(trim, ''))), LOWER(TRIM(COALESCE(title, ''))));

-- ============================================================
-- 2. Update sync function to use custommaketext, customtypetext, customconditiontext, custom_model_trim
-- ============================================================
CREATE OR REPLACE FUNCTION public.run_normalized_inventory_from_scrap(p_date date DEFAULT CURRENT_DATE)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_inserted bigint;
  v_pull_ts  timestamptz := clock_timestamp();
BEGIN
  IF p_date IS NULL THEN
    p_date := CURRENT_DATE;
  END IF;

  INSERT INTO public.normalized_inventory_from_scrap (
    customer_id, track_date, pull_date, pull_date_time,
    "condition", year, make, model, vin, advertiser, color, description,
    doors, drivetrain, formatted_price, fuel_type, image_type, image_url,
    location, mileage, price, title, transmission, trim, type, url, vehicle_type,
    custom_label_0, custom_label_1, custom_label_2, custom_label_3, custom_label_4,
    custom_type, rv_type, rv_category, rv_class, category, motorhome_class,
    custom_make, custom_type_2, custom_condition, cms, sale_tag, stock_number, msrp,
    custom_model, custom_trim
  )
  SELECT
    c.id,
    r.creation_date,
    r.creation_date,
    v_pull_ts,
    r.condition_,
    r.year_,
    r.make,
    r.model,
    r.vin,
    COALESCE(r.dealer_url, '')::varchar(255),
    COALESCE(r.exterior_color, '')::varchar(255),
    r.description,
    r.doors,
    r.drivetrain,
    r.price,
    r.fuel_type,
    ''::varchar(255),
    r.image_url,
    CASE
      WHEN c.id IN (143, 144, 145, 146, 147, 150, 151) THEN 'Location one'
      ELSE COALESCE(REPLACE(r.location, ',', ''), '')
    END,
    TRIM(COALESCE(r.mileage_value, '') || ' ' || COALESCE(r.mileage_unit, ''))::varchar(255),
    COALESCE(NULLIF(TRIM(REGEXP_REPLACE(COALESCE(r.price, ''), '[,$]', '', 'g')), ''), '0.00')::varchar(255),
    r.title,
    r.transmission,
    r.trim,
    r.type_,
    COALESCE(r.url, '')::varchar(255),
    ''::varchar(255),
    r.custom_label_0,
    r.custom_label_1,
    r.custom_label_2,
    ''::varchar(255),
    ''::varchar(255),
    TRIM(COALESCE(r.type_, '') || CASE WHEN COALESCE(TRIM(r.sub_type), '') <> '' THEN ' ' || r.sub_type ELSE '' END)::varchar(255),
    ''::varchar(255),
    ''::varchar(255),
    ''::varchar(255),
    r.sub_type,
    ''::varchar(255),
    COALESCE((SELECT cm.custom_make_text FROM public.custommaketext cm WHERE LOWER(TRIM(COALESCE(r.make, ''))) = LOWER(cm.make_text) LIMIT 1), '')::varchar(255),
    COALESCE((SELECT ct.custom_type_text FROM public.customtypetext ct
      WHERE LOWER(TRIM(COALESCE(r.type_, '') || CASE WHEN COALESCE(TRIM(r.sub_type), '') <> '' THEN ' ' || r.sub_type ELSE '' END)) = LOWER(ct.type_text) LIMIT 1), '')::varchar(255),
    COALESCE((SELECT cc.custom_condition_text FROM public.customconditiontext cc
      WHERE LOWER(TRIM(COALESCE(r.condition_, ''))) = LOWER(cc.condition_text) LIMIT 1), '')::varchar(255),
    r.cms,
    r.special_tag,
    r.stock_number,
    r.msrp,
    COALESCE((SELECT cmt.custom_model FROM public.custom_model_trim cmt
      WHERE LOWER(TRIM(COALESCE(r.model, ''))) = LOWER(TRIM(COALESCE(cmt.model, '')))
        AND LOWER(TRIM(COALESCE(r.trim, ''))) = LOWER(TRIM(COALESCE(cmt.trim, '')))
        AND LOWER(TRIM(COALESCE(r.title, ''))) = LOWER(TRIM(COALESCE(cmt.title, ''))) LIMIT 1), '')::varchar(255),
    COALESCE((SELECT cmt.custom_trim FROM public.custom_model_trim cmt
      WHERE LOWER(TRIM(COALESCE(r.model, ''))) = LOWER(TRIM(COALESCE(cmt.model, '')))
        AND LOWER(TRIM(COALESCE(r.trim, ''))) = LOWER(TRIM(COALESCE(cmt.trim, '')))
        AND LOWER(TRIM(COALESCE(r.title, ''))) = LOWER(TRIM(COALESCE(cmt.title, ''))) LIMIT 1), '')::varchar(255)
  FROM public.scrap_rawdata r
  INNER JOIN public.clients c
    ON c.dealership_name IS NOT NULL AND TRIM(c.dealership_name) <> ''
   AND c.is_active = TRUE
   AND c.dealership_name = r.dealership_name
  WHERE r.creation_date = p_date
  ON CONFLICT (customer_id, pull_date, vin, url) DO NOTHING;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;
  RETURN jsonb_build_object('date', p_date, 'rows_inserted', v_inserted, 'status', 'ok');
END;
$$;

-- ============================================================
-- 3. Seed data (from MySQL base_* tables). ON CONFLICT DO NOTHING.
-- ============================================================

-- customtypetext
INSERT INTO public.customtypetext (type_text, custom_type_text)
VALUES
  ('Convertible', 'Convertible'),
  ('Coupe', 'Coupe'),
  ('Hatchback', 'Hatchback'),
  ('Minivan', 'Van'),
  ('Passenger Sedan', 'Sedan'),
  ('Sedan', 'Sedan'),
  ('SUV', 'SUV'),
  ('Truck', 'Pick Up Truck'),
  ('Van', 'Van'),
  ('Wagon', 'Wagon'),
  ('A-Frames', 'Pop-up Campers'),
  ('BOAT', 'Boat'),
  ('Boat Trailer', 'Boat'),
  ('Car', 'Car'),
  ('Class A', 'Class A Motorhomes'),
  ('Class A Diesel', 'Class A Motorhomes'),
  ('Class A Diesel Motorhome', 'Class A Motorhomes')
ON CONFLICT (type_text) DO NOTHING;

-- custommaketext (sample from MySQL)
INSERT INTO public.custommaketext (make_text, custom_make_text)
VALUES
  ('17SBH', 'Coachmen'),
  ('CLIPPER', 'Coachmen'),
  ('FREEDOM EXPRESS', 'Freedom RV'),
  ('Adventurer', 'Adventurer'),
  ('Airstream', 'Airstream'),
  ('ALLIANCE', 'Alliance RV'),
  ('Alliance RV', 'Alliance RV'),
  ('Alliance Rv', 'Alliance RV'),
  ('VIKING', 'Forest River RV'),
  ('ROC Trailers', 'ROC Trailers'),
  ('C5', 'C5'),
  ('Can-Am', 'Can-Am'),
  ('DENAGO', 'Denago'),
  ('EZ Loader', 'EZ Loader')
ON CONFLICT (make_text) DO NOTHING;

-- customconditiontext
INSERT INTO public.customconditiontext (condition_text, custom_condition_text)
VALUES
  ('New', 'New'),
  ('Used', 'Used'),
  ('Certified', 'Used'),
  ('Pre-owned', 'Used'),
  ('Consignmen', 'Other Condition'),
  ('Consignment', 'Other Condition'),
  ('Vacation C', 'Other Condition'),
  ('USED 2007', 'Other Condition'),
  ('9 2', 'Other Condition'),
  ('JAVELIN 17', 'Other Condition'),
  ('Other', 'Other Condition'),
  ('PreOwned', 'Used'),
  ('USED 2007 CROWLINE BOAT 230LS', 'Other Condition'),
  ('EZ GO', 'Other Condition'),
  ('Storage Locker', 'Other Condition'),
  ('Vacation Certified', 'Other Condition')
ON CONFLICT (condition_text) DO NOTHING;

-- custom_model_trim (Bronco examples from MySQL)
INSERT INTO public.custom_model_trim (model, trim, title, custom_model, custom_trim)
VALUES
  ('Bronco', 'Badlands', 'New 2024 Ford Bronco Badlands', 'Bronco', 'Badlands'),
  ('Bronco', 'Base', 'New 2025 Ford Bronco Base', 'Bronco', 'Base'),
  ('Bronco', 'Big Bend', 'Demo 2024 Ford Bronco Big Bend', 'Bronco', 'Big Bend'),
  ('Bronco', 'Badlands', 'New 2024 Ford Bronco Badlands SUV V-6 cyl', 'Bronco', 'Badlands'),
  ('Bronco', 'Black Diamond', 'New 2024 Ford Bronco Black Diamond', 'Bronco', 'Black Diamond'),
  ('Bronco', 'Heritage Limited Edition', 'New 2024 Ford Bronco Heritage Limited Edition', 'Bronco', 'Heritage Limited'),
  ('Bronco', 'Outer Banks', 'Courtesy Vehicle 2024 Ford Bronco Outer Banks', 'Bronco', 'Outer Banks'),
  ('Bronco', 'Raptor', 'New 2024 Ford Bronco Raptor', 'Bronco', 'Raptor')
ON CONFLICT (model, trim, title) DO NOTHING;

-- Grants
GRANT SELECT ON public.custommaketext TO service_role;
GRANT SELECT ON public.customtypetext TO service_role;
GRANT SELECT ON public.customconditiontext TO service_role;
GRANT SELECT ON public.custom_model_trim TO service_role;

COMMENT ON TABLE public.customtypetext IS 'Lookup: type_text -> custom_type_text (from MySQL base_customtypetext).';
COMMENT ON TABLE public.custommaketext IS 'Lookup: make_text -> custom_make_text (from MySQL base_custommaketext).';
COMMENT ON TABLE public.customconditiontext IS 'Lookup: condition_text -> custom_condition_text (from MySQL base_customconditiontext).';
COMMENT ON TABLE public.custom_model_trim IS 'Lookup: (model, trim, title) -> (custom_model, custom_trim) (from MySQL base_custom_model_trim).';
