-- ============================================================
-- Scrap rawdata -> normalized_inventory_from_scrap daily sync
-- Run via pg_cron daily at 02:30, or manually:
--   SELECT run_normalized_inventory_from_scrap(CURRENT_DATE);
--   SELECT run_normalized_inventory_from_scrap('2026-03-17'::date);
-- ============================================================

-- ============================================================
-- 1. Source table: scrap_rawdata (for current-date scrap data)
--    Expected columns to match Python script usage.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.scrap_rawdata (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dealership_name   varchar(255),
  creation_date     date,
  advertiser        varchar(255),
  cms              varchar(255),
  "condition"      varchar(255),
  year             varchar(255),
  make             varchar(255),
  model            varchar(255),
  vin              varchar(255),
  stock_number     varchar(255),
  url              varchar(255),
  msrp             varchar(255),
  formatted_price   varchar(255),
  type             varchar(255),
  category         varchar(255),
  location         varchar(255),
  image_url        varchar(255),
  description      varchar(255),
  title            varchar(255),
  trim             varchar(255),
  doors            varchar(255),
  drivetrain       varchar(255),
  fuel_type        varchar(255),
  color            varchar(255),
  mileage          varchar(255),
  transmission     varchar(255),
  custom_label_0   varchar(255),
  custom_label_1   varchar(255),
  custom_label_2   varchar(255)
);

CREATE INDEX IF NOT EXISTS idx_scrap_rawdata_dealership_creation
  ON public.scrap_rawdata (dealership_name, creation_date);

COMMENT ON TABLE public.scrap_rawdata IS 'Raw scrap data; sync runs daily into normalized_inventory_from_scrap.';

-- ============================================================
-- 2. Mapping: client_id (Supabase clients.id) <-> dealership_name (in scrap_rawdata)
--    Populate this so sync knows which scrap rows belong to which customer.
--    Requires public.clients to exist; add FK if desired: REFERENCES public.clients(id) ON DELETE CASCADE
-- ============================================================
CREATE TABLE IF NOT EXISTS public.client_dealership_mapping (
  client_id        integer NOT NULL,
  dealership_name  varchar(255) NOT NULL,
  PRIMARY KEY (client_id),
  UNIQUE (dealership_name)
);

COMMENT ON TABLE public.client_dealership_mapping IS 'Maps clients to scrap_rawdata.dealership_name for daily sync. Populate with (client_id, dealership_name) from your scrap source.';

-- ============================================================
-- 3. Sync function: copy current-date rows from scrap_rawdata
--    into normalized_inventory_from_scrap (one run per date).
--    Uses ON CONFLICT DO NOTHING to match Python ignore_conflicts=True.
--    Best performance: single INSERT...SELECT in DB, no Edge timeout.
-- ============================================================
CREATE OR REPLACE FUNCTION public.run_normalized_inventory_from_scrap(p_date date DEFAULT CURRENT_DATE)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_inserted bigint;
  v_pull_ts  timestamptz := clock_timestamp();
BEGIN
  IF p_date IS NULL THEN
    p_date := CURRENT_DATE;
  END IF;

  INSERT INTO public.normalized_inventory_from_scrap (
    customer_id, track_date, pull_date, pull_date_time,
    "condition", year, make, model, vin, advertiser, color, description,
    doors, drivetrain, formatted_price, fuel_type, image_type, image_url,
    location, mileage, price, title, transmission, trim, type, url, vehicle_type,
    custom_label_0, custom_label_1, custom_label_2, custom_label_3, custom_label_4,
    custom_type, rv_type, rv_category, rv_class, category, motorhome_class,
    custom_make, custom_type_2, custom_condition, cms, sale_tag, stock_number, msrp,
    custom_model, custom_trim
  )
  SELECT
    m.client_id,
    r.creation_date,
    r.creation_date,
    v_pull_ts,
    r."condition",
    r.year,
    r.make,
    r.model,
    r.vin,
    r.advertiser,
    r.color,
    r.description,
    r.doors,
    r.drivetrain,
    r.formatted_price,
    r.fuel_type,
    ''::varchar(255),
    r.image_url,
    CASE
      WHEN m.client_id IN (143, 144, 145, 146, 147, 150, 151) THEN 'Location one'
      ELSE COALESCE(REPLACE(r.location, ',', ''), '')
    END,
    r.mileage,
    COALESCE(
      NULLIF(TRIM(REGEXP_REPLACE(COALESCE(r.formatted_price, ''), '[,$]', '', 'g')), ''),
      '0.00'
    )::varchar(255),
    r.title,
    r.transmission,
    r.trim,
    r.type,
    r.url,
    ''::varchar(255),
    r.custom_label_0,
    r.custom_label_1,
    r.custom_label_2,
    ''::varchar(255),
    ''::varchar(255),
    r.type,
    ''::varchar(255),
    ''::varchar(255),
    ''::varchar(255),
    r.category,
    ''::varchar(255),
    r.make,
    r.type,
    r."condition",
    r.cms,
    r.custom_label_0,
    r.stock_number,
    r.msrp,
    r.model,
    r.trim
  FROM public.scrap_rawdata r
  INNER JOIN public.client_dealership_mapping m ON m.dealership_name = r.dealership_name
  WHERE r.creation_date = p_date
  ON CONFLICT (customer_id, pull_date, vin, url) DO NOTHING;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  RETURN jsonb_build_object(
    'date', p_date,
    'rows_inserted', v_inserted,
    'status', 'ok'
  );
END;
$$;

-- Unique constraint required for ON CONFLICT (customer_id, pull_date, vin, url)
-- We already have a UNIQUE INDEX on those columns; PostgreSQL allows ON CONFLICT on unique index columns.
-- If the index was created without a constraint name, ON CONFLICT (col1, col2, ...) still works.

-- ============================================================
-- 4. Grants (for cron / service role)
-- ============================================================
GRANT SELECT, INSERT ON public.scrap_rawdata TO service_role;
GRANT SELECT ON public.client_dealership_mapping TO service_role;
GRANT SELECT, INSERT ON public.normalized_inventory_from_scrap TO service_role;
GRANT EXECUTE ON FUNCTION public.run_normalized_inventory_from_scrap(date) TO service_role;
GRANT EXECUTE ON FUNCTION public.run_normalized_inventory_from_scrap(date) TO postgres;

-- ============================================================
-- 5. Daily cron: run sync for current date (e.g. 2:30 AM)
-- ============================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'normalized-inventory-from-scrap-daily') THEN
    PERFORM cron.unschedule('normalized-inventory-from-scrap-daily');
  END IF;
END $$;

SELECT cron.schedule(
  'normalized-inventory-from-scrap-daily',
  '30 2 * * *',
  $$SELECT public.run_normalized_inventory_from_scrap(CURRENT_DATE)$$
);
